global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['whaticket_node_exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['whaticket_postgres_exporter:9187']