export const mimeToExtension: { [key: string]: string } = {
  'audio/aac': 'aac',
  'application/x-abiword': 'abw',
  'application/octet-stream': 'arc',
  'video/x-msvideo': 'avi',
  'application/vnd.amazon.ebook': 'azw',
  'application/x-bzip': 'bz',
  'application/x-bzip2': 'bz2',
  'application/x-csh': 'csh',
  'text/css': 'css',
  'text/csv': 'csv',
  'text/plain': 'txt',
  'application/msword': 'doc',
  'application/vnd.ms-fontobject': 'eot',
  'application/epub+zip': 'epub',
  'image/gif': 'gif',
  'text/html': 'html',
  'image/x-icon': 'ico',
  'text/calendar': 'ics',
  'image/jpeg': 'jpg',
  'application/json': 'json',
  'audio/midi': 'midi',
  'video/mpeg': 'mpeg',
  'application/vnd.apple.installer+xml': 'mpkg',
  'audio/ogg': 'oga',
  'video/ogg': 'ogv',
  'application/ogg': 'ogx',
  'font/otf': 'otf',
  'image/png': 'png',
  'application/pdf': 'pdf',
  'application/vnd.ms-powerpoint': 'ppt',
  'application/x-rar-compressed': 'rar',
  'application/rtf': 'rtf',
  'application/x-sh': 'sh',
  'image/svg+xml': 'svg',
  'application/x-shockwave-flash': 'swf',
  'application/x-tar': 'tar',
  'image/tiff': 'tiff',
  'application/typescript': 'ts',
  'font/ttf': 'ttf',
  'application/vnd.visio': 'vsd',
  'audio/x-wav': 'wav',
  'audio/webm': 'weba',
  'video/webm': 'webm',
  'image/webp': 'webp',
  'font/woff': 'woff',
  'font/woff2': 'woff2',
  'application/xhtml+xml': 'xhtml',
  'application/xml': 'xml',
  'video/3gpp': '3gp',
  'audio/3gpp': '3gp',
  'video/3gpp2': '3g2',
  'audio/3gpp2': '3g2',
};

export function convertMimeTypeToExtension(mimetype: string) {
  return mimeToExtension[mimetype];
}
